# Generated by Django 5.1.7 on 2025-08-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('child_id', models.AutoField(db_column='childid', primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, db_column='fullname', max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, db_column='dateofbirth', null=True)),
            ],
            options={
                'db_table': 'children',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('otp_id', models.AutoField(db_column='otp_id', primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_in', models.IntegerField(default=300)),
            ],
            options={
                'db_table': 'otp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Membershipapplication',
            fields=[
                ('application_id', models.AutoField(db_column='applicationid', primary_key=True, serialize=False)),
                ('date_accomplished', models.DateField(auto_now_add=True, db_column='dateaccomplished')),
                ('emergency_contact_name', models.CharField(db_column='emergencycontactname', max_length=100)),
                ('emergency_contact_address', models.TextField(db_column='emergencycontactaddress')),
                ('status', models.CharField(default='Pending', max_length=10)),
            ],
            options={
                'db_table': 'membershipapplication',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personalinfo',
            fields=[
                ('person_id', models.AutoField(db_column='personid', primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=50)),
                ('first_name', models.CharField(db_column='firstname', max_length=50)),
                ('name_extension', models.CharField(blank=True, db_column='nameextension', max_length=5, null=True)),
                ('middle_name', models.CharField(blank=True, db_column='middlename', max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, db_column='dateofbirth', null=True)),
                ('place_of_birth', models.TextField(blank=True, db_column='placeofbirth', null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('civil_status', models.CharField(blank=True, db_column='civilstatus', max_length=20, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=50, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_type', models.CharField(blank=True, db_column='bloodtype', max_length=5, null=True)),
                ('gsis_id_no', models.CharField(blank=True, max_length=30, null=True)),
                ('pagibig_id_no', models.CharField(blank=True, db_column='pagibig_no', max_length=30, null=True)),
                ('philhealth_id_no', models.CharField(blank=True, db_column='philhealth_no', max_length=20, null=True)),
                ('sss_id_no', models.CharField(blank=True, db_column='sss_no', max_length=20, null=True)),
                ('residential_address', models.TextField(db_column='residentialaddress')),
                ('residential_address_zip_code', models.CharField(db_column='residentialaddresszipcode', max_length=10)),
                ('residential_address_telephone_no', models.CharField(blank=True, db_column='residentialaddresstelno', max_length=15, null=True)),
                ('permanent_address', models.TextField(db_column='permanentaddress')),
                ('permanent_address_zip_code', models.CharField(blank=True, db_column='permanentaddresszipcode', max_length=10, null=True)),
                ('permanent_address_telephone_no', models.CharField(blank=True, db_column='permanentaddresstelno', max_length=15, null=True)),
                ('contact_email_address', models.CharField(blank=True, db_column='contactemailaddress', max_length=100, null=True)),
                ('cellphone_no', models.CharField(blank=True, db_column='cellphoneno', max_length=15, null=True)),
                ('agency_employee_no', models.CharField(db_column='agencyemployeeno', max_length=50)),
                ('tin_no', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'personalinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Spouse',
            fields=[
                ('spouse_id', models.AutoField(db_column='spouseid', primary_key=True, serialize=False)),
                ('spouse_first_name', models.CharField(blank=True, db_column='firstname', max_length=50, null=True)),
                ('spouse_middle_name', models.CharField(blank=True, db_column='middlename', max_length=50, null=True)),
                ('spouse_surname', models.CharField(blank=True, db_column='surname', max_length=50, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('employer_business_name', models.CharField(blank=True, db_column='employerbusinessname', max_length=100, null=True)),
                ('business_address', models.TextField(blank=True, db_column='businessaddress', null=True)),
                ('telephone_no', models.CharField(blank=True, db_column='telephoneno', max_length=20, null=True)),
            ],
            options={
                'db_table': 'spouse',
                'managed': False,
            },
        ),
    ]
