# Generated by Django 5.1.7 on 2025-09-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('emergency_contact_id', models.AutoField(db_column='emergency_contact_id', primary_key=True, serialize=False)),
                ('emergency_contact_name', models.CharField(db_column='emergency_contact_name', max_length=100)),
                ('emergency_contact_address', models.TextField(db_column='emergency_contact_address')),
            ],
            options={
                'db_table': 'emergencycontact',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
