# Generated by Django 5.1.7 on 2025-08-17 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('savings_id', models.AutoField(db_column='savingsid', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(db_column='amount', decimal_places=2, max_digits=12)),
                ('member_id', models.ForeignKey(db_column='memberid', on_delete=django.db.models.deletion.DO_NOTHING, to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.AutoField(db_column='transactionid', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(db_column='amount', decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('Loan Payment', 'Loan Payment'), ('Savings Deposit', 'Savings Deposit'), ('Withdrawal', 'Withdrawal')], db_column='transactiontype', max_length=30)),
                ('transaction_date', models.DateTimeField(auto_now_add=True, db_column='date')),
                ('cashier_id', models.ForeignKey(db_column='cashierid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='cashier_transactions', to=settings.AUTH_USER_MODEL)),
                ('member_id', models.ForeignKey(db_column='memberid', on_delete=django.db.models.deletion.DO_NOTHING, to='members.member')),
            ],
        ),
    ]
