# Generated by Django 5.1.7 on 2025-09-25 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='Savings',
        ),
    ]
