# Generated by Django 5.1.7 on 2025-09-25 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transactions_options_delete_savings'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transactions',
            table='transactions',
        ),
    ]
