# Generated by Django 5.1.7 on 2025-08-17 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('appointment_id', models.AutoField(db_column='appointmentid', primary_key=True, serialize=False)),
                ('appointment_date', models.DateField(db_column='date')),
                ('appointment_time', models.TimeField(db_column='time')),
                ('appointment_type', models.CharField(choices=[('Consultation', 'Consultation'), ('Follow-up', 'Follow-up'), ('Inquiry', 'Inquiry')], db_column='appointmenttype', max_length=15)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled')], db_column='status', default='Pending', max_length=20)),
                ('bookkeeper_id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookkeeper_appointments', to=settings.AUTH_USER_MODEL)),
                ('member_id', models.ForeignKey(db_column='memberid', on_delete=django.db.models.deletion.DO_NOTHING, to='members.member')),
            ],
        ),
    ]
