# Generated by Django 5.1.7 on 2025-09-25 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointments_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointments',
            table='appointments',
        ),
    ]
