# Generated by Django 5.1.7 on 2025-08-17 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('loan_application_id', models.AutoField(db_column='loanapplicationid', primary_key=True, serialize=False)),
                ('loan_type', models.CharField(db_column='loantype', max_length=50)),
                ('loan_amount', models.DecimalField(db_column='loanamount', decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(db_column='interestrate', decimal_places=2, max_digits=5)),
                ('loan_term_years', models.PositiveIntegerField(db_column='loantermyears')),
                ('loan_term_months', models.PositiveIntegerField(db_column='loantermmonths')),
                ('loan_term_days', models.PositiveIntegerField(db_column='loantermdays')),
                ('total_payable', models.DecimalField(db_column='totalpayable', decimal_places=2, max_digits=12)),
                ('monthly_amortization', models.DecimalField(db_column='monthlyamortization', decimal_places=2, max_digits=12)),
                ('cbu', models.DecimalField(db_column='cbu', decimal_places=2, max_digits=12)),
                ('insurance', models.DecimalField(db_column='insurance', decimal_places=2, max_digits=12)),
                ('service_charge', models.DecimalField(db_column='servicecharge', decimal_places=2, max_digits=12)),
                ('net_proceeds', models.DecimalField(db_column='netproceeds', decimal_places=2, max_digits=12)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('verified_date', models.DateField(blank=True, db_column='verifieddate', null=True)),
                ('approved_date', models.DateField(blank=True, db_column='approveddate', null=True)),
                ('approver_id', models.ForeignKey(blank=True, db_column='approverid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL)),
                ('member_id', models.ForeignKey(db_column='memberid', on_delete=django.db.models.deletion.DO_NOTHING, to='members.member')),
                ('verifier_id', models.ForeignKey(blank=True, db_column='verifierid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_loans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(db_column='loanid', primary_key=True, serialize=False)),
                ('outstanding_balance', models.DecimalField(db_column='outstandingbalance', decimal_places=2, max_digits=12)),
                ('loan_status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed')], db_column='loanstatus', default='Active', max_length=20)),
                ('released_date', models.DateField(auto_now_add=True, db_column='releaseddate')),
                ('member_id', models.ForeignKey(db_column='memberid', on_delete=django.db.models.deletion.DO_NOTHING, to='members.member')),
                ('released_by_id', models.ForeignKey(db_column='releasedbyid', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('loan_application_id', models.ForeignKey(db_column='loanapplicationid', on_delete=django.db.models.deletion.DO_NOTHING, to='loans.loanapplication')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepaymentSchedule',
            fields=[
                ('schedule_id', models.AutoField(db_column='scheduleid', primary_key=True, serialize=False)),
                ('due_date', models.DateField(db_column='duedate')),
                ('amount_due', models.DecimalField(db_column='amountdue', decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Due', 'Due'), ('Overdue', 'Overdue'), ('Paid', 'Paid'), ('Partially Paid', 'Partially Paid')], db_column='status', default='Pending', max_length=20)),
                ('paid_date', models.DateField(blank=True, db_column='paiddate', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdate')),
                ('loan_id', models.ForeignKey(db_column='loanid', on_delete=django.db.models.deletion.DO_NOTHING, to='loans.loan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanPenalty',
            fields=[
                ('penalty_id', models.AutoField(db_column='penaltyid', primary_key=True, serialize=False)),
                ('penalty_amount', models.DecimalField(db_column='penaltyamount', decimal_places=2, max_digits=12)),
                ('days_overdue', models.IntegerField(db_column='daysoverdue')),
                ('date_evaluated', models.DateField(db_column='dateevaluated')),
                ('schedule_id', models.ForeignKey(db_column='scheduleid', on_delete=django.db.models.deletion.DO_NOTHING, to='loans.loanrepaymentschedule')),
            ],
        ),
    ]
