# Generated by Django 5.1.7 on 2025-09-25 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='loanapplication',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='loanpenalty',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='loanrepaymentschedule',
            options={'managed': False},
        ),
    ]
