# Generated by Django 5.1.7 on 2025-09-25 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loan_options_alter_loanapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loan',
            table='loan',
        ),
        migrations.AlterModelTable(
            name='loanapplication',
            table='loanapplication',
        ),
        migrations.AlterModelTable(
            name='loanpenalty',
            table='loanpenalty',
        ),
        migrations.AlterModelTable(
            name='loanrepaymentschedule',
            table='loanrepaymentschedule',
        ),
    ]
