# Generated by Django 5.1.7 on 2025-08-17 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Financialreports',
            fields=[
                ('report_id', models.AutoField(db_column='reportid', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdat')),
            ],
        ),
        migrations.CreateModel(
            name='Memberfinancialdata',
            fields=[
                ('member_financial_id', models.AutoField(db_column='memberfinancialid', primary_key=True, serialize=False)),
                ('account_number', models.CharField(db_column='accountnumber', max_length=50)),
                ('name', models.CharField(db_column='name', max_length=150)),
                ('outstanding_balance', models.DecimalField(db_column='outstandingbalance', decimal_places=2, max_digits=12)),
                ('penalty_charge', models.DecimalField(db_column='penaltycharge', decimal_places=2, max_digits=12)),
                ('savings_after_deduction', models.DecimalField(db_column='savingsafterdeduction', decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(db_column='remarks')),
                ('report_id', models.ForeignKey(db_column='reportid', on_delete=django.db.models.deletion.DO_NOTHING, to='financial_reporting.financialreports')),
            ],
        ),
    ]
