# Generated by Django 5.1.7 on 2025-09-25 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialreports',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='memberfinancialdata',
            options={'managed': False},
        ),
    ]
