# Generated by Django 5.1.7 on 2025-09-25 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_reporting', '0002_alter_financialreports_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='financialreports',
            table='financialreports',
        ),
        migrations.AlterModelTable(
            name='memberfinancialdata',
            table='memberfinancialdata',
        ),
    ]
