# Generated by Django 5.1.7 on 2025-08-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(db_column='memberid', primary_key=True, serialize=False)),
                ('account_number', models.CharField(db_column='accountnumber', max_length=50)),
                ('membership_date', models.DateField(auto_now_add=True, db_column='membershipdate')),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
    ]
