# Generated by Django 5.1.7 on 2025-09-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('savings_id', models.AutoField(db_column='savingid', primary_key=True, serialize=False)),
                ('balance', models.DecimalField(db_column='balance', decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'db_table': 'savings',
                'managed': False,
            },
        ),
    ]
