# Generated by Django 5.1.7 on 2025-09-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('otp_id', models.AutoField(db_column='otp_id', primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('otp_code', models.CharField(db_column='otp_code', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_in', models.IntegerField(default=300)),
            ],
            options={
                'db_table': 'otp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(db_column='notification_id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=255)),
                ('message', models.TextField(db_column='message')),
                ('notification_type', models.CharField(blank=True, choices=[('info', 'Info'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error')], db_column='notification_type', max_length=20, null=True)),
                ('is_read', models.BooleanField(db_column='is_read', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'notifications',
                'managed': False,
            },
        ),
    ]
